services:
  postgres_local:
    image: postgres:13
    container_name: alembic_poc_local_dev
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password_dev
      POSTGRES_DB: db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
  postgres_production:
    image: postgres:13
    container_name: alembic_poc_production
    environment:
      POSTGRES_USER: user_prod
      POSTGRES_PASSWORD: password_prod
      POSTGRES_DB: db_prod
    networks:
      - my_network
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
volumes:
  postgres_data_dev:
    driver: local
  postgres_data_prod:
    driver: local

networks:
  my_network:
    driver: bridge